language: node_js
node_js:
  - "stable"
services:
  - mongodb
cache:
  directories:
  - node_modules
  
before_script:
  - git submodule update --init --recursive
  - git submodule foreach --recursive git fetch
  - git submodule foreach git merge origin master
env:
  - NODE_ENV=development
notifications:
 slack: yolotech:6AMpaXbYBROjNrdrbsRGsz1T
