#!/usr/bin/env node
var debug = require('debug')('resty:server');
var server = require('../server');
var Config = require('../server/Config/Config');

var socketer = require('../lib/socket');

server.set('port', process.env.PORT || 3000);

var serverInstance = server.listen(server.get('port'), function() {
  //debug('Express server listening on port ' + serverInstance.address().port);
  console.log('Express server listening on port ' + serverInstance.address().port);
  console.log('------------------------------------');
  console.log('Api running at http://localhost:' + serverInstance.address().port + '/' + Config.apiVersion + '/');
  console.log('------------------------------------');
  console.log('Please read project wiki for more info on Api Authentcation and endpoints');
  console.log('------------------------------------');
  console.log('You can browse the frontend at http://localhost:' + serverInstance.address().port + '/');
  console.log('------------------------------------');
  //console.log('Socket server listening at ');
});

socketer.boot(serverInstance);